### ISSUE TITLE
Bounds for GHC 9.1

### ISSUE THREAD

**Issue by Mikolaj** [haskell-hvr/int-cast#6]
Hi @hvr!

I'm a user of this excellent package and I've noticed the bounds are too restrictive for GHC 9.1 that is already released. Also, the bounds for QuickCheck are stricter than they'd need to be. Would you like to fix those on Hackage? Or can I help, e.g., by preparing a PR and possibly making a release? I may even take over the package temporarily, if you wish so, until you feel like maintaining it again.

All the best,
Mikolaj

**Comment by Bodigrim** [comment]
As a Hackage Trustee, I made a required revision: http://hackage.haskell.org/package/int-cast-0.2.0.0/revisions/

**Comment by Mikolaj** [comment]
@Bodigrim: thank you so much. I've just ran my LambdaHack CI and it works great now.
